import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/components/providers/index";

import Header from "@/components/ui/custom/header";
import { Cart } from "@/components/ui/custom/cart";
import Hydration from "@/store/hydration";
import { Suspense } from "react";

import "./globals.css";
import Loading from "@/components/ui/custom/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loading message="Loading..." />}>
          <Providers>
            <Hydration />
            <Header />
            <main className="container grid grid-cols-12 md:gap-6 my-8">
              <div className="col-span-10">{children}</div>
              <div className="col-span-2">
                <Cart />
              </div>
            </main>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
